export enum AuditAction {
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  PASSWORD_CHANGED_BY_ADMIN = 'PASSWORD_CHANGED_BY_ADMIN',
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  NOTIFICATION_CREATED = 'NOTIFICATION_CREATED',
  SERVICE_CATEGORY_CREATED = 'SERVICE_CATEGORY_CREATED',
  SERVICE_CATEGORY_UPDATED = 'SERVICE_CATEGORY_UPDATED',
  SERVICE_CATEGORY_DELETED = 'SERVICE_CATEGORY_DELETED',
  DIVISION_CATEGORY_CREATED = 'DIVISION_CATEGORY_CREATED',
  DIVISION_CATEGORY_UPDATED = 'DIVISION_CATEGORY_UPDATED',
  DIVISION_CATEGORY_DELETED = 'DIVISION_CATEGORY_DELETED',
  DIVISION_CREATED = 'DIVISION_CREATED',
  DIVISION_UPDATED = 'DIVISION_UPDATED',
  DIVISION_DELETED = 'DIVISION_DELETED',

  // Bookings
  BOOKING_CREATED = 'BOOKING_CREATED',
  BOOKING_STATUS_UPDATED = 'BOOKING_STATUS_UPDATED',
}
