export enum AuditAction {
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  PASSWORD_CHANGED_BY_ADMIN = 'PASSWORD_CHANGED_BY_ADMIN',
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  NOTIFICATION_CREATED = 'NOTIFICATION_CREATED',
}
