export enum AuditAction {
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  PASSWORD_CHANGED_BY_ADMIN = 'PASSWORD_CHANGED_BY_ADMIN',
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  NOTIFICATION_CREATED = 'NOTIFICATION_CREATED',
  SERVICE_CATEGORY_CREATED = 'SERVICE_CATEGORY_CREATED',
  SERVICE_CATEGORY_UPDATED = 'SERVICE_CATEGORY_UPDATED',
  SERVICE_CATEGORY_DELETED = 'SERVICE_CATEGORY_DELETED',
  DIVISION_CATEGORY_CREATED = 'DIVISION_CATEGORY_CREATED',
  DIVISION_CATEGORY_UPDATED = 'DIVISION_CATEGORY_UPDATED',
  DIVISION_CATEGORY_DELETED = 'DIVISION_CATEGORY_DELETED',
  DIVISION_CREATED = 'DIVISION_CREATED',
  DIVISION_UPDATED = 'DIVISION_UPDATED',
  DIVISION_DELETED = 'DIVISION_DELETED',

  NEWS_EVENT_CREATED = 'NEWS_EVENT_CREATED',
  NEWS_EVENT_UPDATED = 'NEWS_EVENT_UPDATED',
  NEWS_EVENT_PUBLISHED = 'NEWS_EVENT_PUBLISHED',
  NEWS_EVENT_UNPUBLISHED = 'NEWS_EVENT_UNPUBLISHED',
  NEWS_EVENT_DELETED = 'NEWS_EVENT_DELETED',

  BLOG_CATEGORY_CREATED = 'BLOG_CATEGORY_CREATED',
  BLOG_CATEGORY_UPDATED = 'BLOG_CATEGORY_UPDATED',
  BLOG_CATEGORY_DELETED = 'BLOG_CATEGORY_DELETED',
  BLOG_CREATED = 'BLOG_CREATED',
  BLOG_UPDATED = 'BLOG_UPDATED',
  BLOG_SUBMITTED = 'BLOG_SUBMITTED',
  BLOG_PUBLISHED = 'BLOG_PUBLISHED',
  BLOG_REJECTED = 'BLOG_REJECTED',
  BLOG_FEATURED = 'BLOG_FEATURED',
  BLOG_UNFEATURED = 'BLOG_UNFEATURED',
  BLOG_DELETED = 'BLOG_DELETED',

  // Bookings
  BOOKING_CREATED = 'BOOKING_CREATED',
  BOOKING_STATUS_UPDATED = 'BOOKING_STATUS_UPDATED',

  // Corporate Network
  NETWORK_RELATION_CREATED = 'NETWORK_RELATION_CREATED',
  NETWORK_RELATION_UPDATED = 'NETWORK_RELATION_UPDATED',
  NETWORK_RELATION_DELETED = 'NETWORK_RELATION_DELETED',
  NETWORK_ENTITY_CREATED = 'NETWORK_ENTITY_CREATED',
  NETWORK_ENTITY_UPDATED = 'NETWORK_ENTITY_UPDATED',
  NETWORK_ENTITY_MOVED = 'NETWORK_ENTITY_MOVED',
  NETWORK_ENTITY_DELETED = 'NETWORK_ENTITY_DELETED',

  // Media Gallery
  MEDIA_TAG_CREATED = 'MEDIA_TAG_CREATED',
  MEDIA_TAG_UPDATED = 'MEDIA_TAG_UPDATED',
  MEDIA_TAG_DELETED = 'MEDIA_TAG_DELETED',
  MEDIA_FOLDER_CREATED = 'MEDIA_FOLDER_CREATED',
  MEDIA_FOLDER_UPDATED = 'MEDIA_FOLDER_UPDATED',
  MEDIA_FOLDER_DELETED = 'MEDIA_FOLDER_DELETED',
  MEDIA_ITEM_CREATED = 'MEDIA_ITEM_CREATED',
  MEDIA_ITEM_UPDATED = 'MEDIA_ITEM_UPDATED',
  MEDIA_ITEM_DELETED = 'MEDIA_ITEM_DELETED',
  // Team & Leadership
  TEAM_MEMBER_CREATED = 'TEAM_MEMBER_CREATED',
  TEAM_MEMBER_UPDATED = 'TEAM_MEMBER_UPDATED',
  TEAM_MEMBER_DELETED = 'TEAM_MEMBER_DELETED',

  // Testimonials
  TESTIMONIAL_SUBMITTED = 'TESTIMONIAL_SUBMITTED',
  TESTIMONIAL_APPROVED = 'TESTIMONIAL_APPROVED',
  TESTIMONIAL_UNAPPROVED = 'TESTIMONIAL_UNAPPROVED',
  TESTIMONIAL_FAVORITED = 'TESTIMONIAL_FAVORITED',
  TESTIMONIAL_UNFAVORITED = 'TESTIMONIAL_UNFAVORITED',
  TESTIMONIAL_DELETED = 'TESTIMONIAL_DELETED',

  // Contact
  CONTACT_SUBMITTED = 'CONTACT_SUBMITTED',
  CONTACT_REVIEWED = 'CONTACT_REVIEWED',
  CONTACT_DELETED = 'CONTACT_DELETED',

  // Awards
  AWARD_CREATED = 'AWARD_CREATED',
  AWARD_UPDATED = 'AWARD_UPDATED',
  AWARD_DELETED = 'AWARD_DELETED',

  // Timeline
  TIMELINE_ITEM_CREATED = 'TIMELINE_ITEM_CREATED',
  TIMELINE_ITEM_UPDATED = 'TIMELINE_ITEM_UPDATED',
  TIMELINE_ITEM_DELETED = 'TIMELINE_ITEM_DELETED',

  // FAQ Category
  FAQ_CATEGORY_CREATED = 'FAQ_CATEGORY_CREATED',
  FAQ_CATEGORY_UPDATED = 'FAQ_CATEGORY_UPDATED',
  FAQ_CATEGORY_DELETED = 'FAQ_CATEGORY_DELETED',

  // FAQ
  FAQ_CREATED = 'FAQ_CREATED',
  FAQ_UPDATED = 'FAQ_UPDATED',
  FAQ_REORDERED = 'FAQ_REORDERED',
  FAQ_DELETED = 'FAQ_DELETED',
}
