// app/news-events/data.ts
import { EventNewsCardProps } from '@/components/client/news-events/EventNewsCard';

export const newsEventsData: EventNewsCardProps[] = [
  {
    id: 'n1',
    type: 'news',
    title: 'New Clinic Opens in Addis Ababa',
    date: '2025-08-20',
    summary: 'Our new clinic opens to serve more patients in Addis Ababa.',
    content: [
      'We are thrilled to announce the opening of our new clinic in the heart of Addis Ababa.',
      'This facility is equipped with state-of-the-art medical technology and top-tier healthcare professionals.',
      'We aim to provide accessible, high-quality healthcare for all patients.',
      'The new clinic expands our ability to serve the growing community with improved access to medical services.',
      'With advanced diagnostic tools and modern patient care units, the clinic sets a new standard for healthcare in the region.',
      'Our mission remains focused on delivering excellence, compassion, and innovation in all aspects of care.',
    ],
    keyHighlights: [
      'State-of-the-art medical equipment',
      'Highly trained medical professionals',
      'Improved accessibility for local communities',
      'Expanded service capacity across Addis Ababa',
      'Focus on patient-centered, modern healthcare',
    ],
    mainImage: 'https://picsum.photos/id/1018/800/400',
    image1: 'https://picsum.photos/id/1015/600/400',
    image2: 'https://picsum.photos/id/1025/600/400',
  },
  {
    id: 'e1',
    type: 'event',
    title: 'Health Awareness Seminar',
    date: '2025-09-15',
    location: 'Liyana Conference Hall, Addis Ababa',
    summary: 'Join our seminar on preventive healthcare and healthy living.',
    content: [
      'We are thrilled to announce the opening of our new clinic in the heart of Addis Ababa.',
      'This facility is equipped with state-of-the-art medical technology and top-tier healthcare professionals.',
      'We aim to provide accessible, high-quality healthcare for all patients.',
      'We are thrilled to announce the opening of our new clinic in the heart of Addis Ababa.',
      'This facility is equipped with state-of-the-art medical technology and top-tier healthcare professionals.',
      'We aim to provide accessible, high-quality healthcare for all patients.',
      'We are thrilled to announce the opening of our new clinic in the heart of Addis Ababa.',
      'This facility is equipped with state-of-the-art medical technology and top-tier healthcare professionals.',
      'We aim to provide accessible, high-quality healthcare for all patients.',
      'We are thrilled to announce the opening of our new clinic in the heart of Addis Ababa.',
      'This facility is equipped with state-of-the-art medical technology and top-tier healthcare professionals.',
      'We aim to provide accessible, high-quality healthcare for all patients.',
      'We are thrilled to announce the opening of our new clinic in the heart of Addis Ababa.',
      'This facility is equipped with state-of-the-art medical technology and top-tier healthcare professionals.',
      'We aim to provide accessible, high-quality healthcare for all patients.',
      'We are thrilled to announce the opening of our new clinic in the heart of Addis Ababa.',
      'This facility is equipped with state-of-the-art medical technology and top-tier healthcare professionals.',
      'We aim to provide accessible, high-quality healthcare for all patients.',
      'We are thrilled to announce the opening of our new clinic in the heart of Addis Ababa.',
      'This facility is equipped with state-of-the-art medical technology and top-tier healthcare professionals.',
      'We aim to provide accessible, high-quality healthcare for all patients.',
      'We are thrilled to announce the opening of our new clinic in the heart of Addis Ababa.',
      'This facility is equipped with state-of-the-art medical technology and top-tier healthcare professionals.',
      'We aim to provide accessible, high-quality healthcare for all patients.',
    ],
    mainImage: 'https://picsum.photos/id/1016/800/400',
    image1: 'https://picsum.photos/id/1039/600/400',
    image2: 'https://picsum.photos/id/1041/600/400',
  },
];
